# Generated by Django 4.1.3 on 2022-11-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_remove_categoria_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_cat',
            new_name='nome',
        ),
    ]
